version: "3.8"
services:
  back-app:
    build: ./backend/
    environment:
      PORT: 6000
      DB_HOST: back-mysql
      DB_USER: root
      DB_PASS: password
      DB: customers_alloc
    ports:
      - 6000:6000
    restart: always
    depends_on:
      - back-mysql

  back-mysql:
    image: mysql:8.0.23
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: customers_alloc
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: "%"

    ports:
      - 3306:3306
    restart: always
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
      - "./backend/db.sql:/docker-entrypoint-initdb.d/1.sql"

  front-app:
    build: ./frontend/customers_allocation/
    command: npm start
    volumes:
      - ./frontend/customers_allocation/:/usr/app
      - /usr/app/node_modules

    ports:
      - 3000:3000
    stdin_open: true
    depends_on:
      - back-app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - back-mysql
    environment:
      PMA_HOST: back-mysql
      PMA_PORT: 3306
    restart: always
    ports:
      - 8081:80

volumes:
  mysql:
  mysql_config:
